// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function ClearAll() {
  return window['go']['main']['App']['ClearAll']();
}

export function ExecuteSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteSkill'](arg1, arg2, arg3);
}

export function ExportFiles(arg1) {
  return window['go']['main']['App']['ExportFiles'](arg1);
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function GetSkills(arg1, arg2) {
  return window['go']['main']['App']['GetSkills'](arg1, arg2);
}

export function OpenFilesDialog() {
  return window['go']['main']['App']['OpenFilesDialog']();
}

export function RemoveSkill(arg1, arg2) {
  return window['go']['main']['App']['RemoveSkill'](arg1, arg2);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}
