// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {executor} from '../models';
import {skills} from '../models';

export function AddFiles(arg1:Array<string>):Promise<Array<session.WorkingFile>>;

export function ClearAll():Promise<void>;

export function ExecuteSkill(arg1:Array<string>,arg2:string,arg3:Record<string, any>):Promise<executor.SkillResult>;

export function ExportFiles(arg1:Array<string>):Promise<Array<session.ExportResult>>;

export function GetSession():Promise<session.SessionSnapshot>;

export function GetSkills(arg1:string,arg2:Array<string>):Promise<Array<skills.Skill>>;

export function OpenFilesDialog():Promise<Array<string>>;

export function RemoveSkill(arg1:string,arg2:number):Promise<session.WorkingFile>;

export function SetMode(arg1:string):Promise<session.SessionSnapshot>;
